<?php
declare(strict_types=1);

// Минимальный словарь RU/KK. Можно расширять постепенно.
return [
  'ru' => [
    'back' => 'Назад',
    'subscription' => 'Подписка',
    'master_subscription' => 'Подписка мастера',
    'plan_select_title' => 'Выбор тарифа',
    'autorenew' => 'Автопродление',
    'autorenew_sub' => 'Списание каждый месяц',
    'current_tariff' => 'Текущий тариф',
    'your_plan' => 'Ваш план',
    'balance' => 'Баланс',
    'plans' => 'Планы',
    'loading' => 'Загрузка...',
    'activate' => 'Активировать',
    'current_plan' => 'Текущий план',
    'change_next_period' => 'Сменить со след. периода',
    'cancel' => 'Отменить',
    'resume' => 'Возобновить',
    'autorenew_on' => 'автопродление: вкл',
    'autorenew_off' => 'автопродление: выкл',
    'active' => 'ACTIVE',
    'inactive' => 'INACTIVE',
    'subscription_inactive' => 'Подписка не активна',
    'confirm_cancel' => 'Отменить автопродление? Подписка будет действовать до конца оплаченного периода.',
    'session_expired' => 'Сессия истекла. Войдите заново.',
    'insufficient_funds' => 'Недостаточно средств.',
    'plan_scheduled' => 'План запланирован. Текущий действует до:',
    'sub_activated_until' => 'Подписка активирована. До:',
    'daily_limit_reached' => 'Дневной лимит принятия заказов исчерпан.',
    'switchToMaster' => 'Стать мастером',
    'switchToClient' => 'Стать клиентом',
  ],
  'kk' => [
    'back' => 'Артқа',
    'subscription' => 'Жазылым',
    'master_subscription' => 'Шебер жазылымы',
    'plan_select_title' => 'Тариф таңдау',
    'autorenew' => 'Автоұзарту',
    'autorenew_sub' => 'Ай сайын автоматты төлем',
    'current_tariff' => 'Ағымдағы тариф',
    'your_plan' => 'Сіздің тариф',
    'balance' => 'Баланс',
    'plans' => 'Тарифтер',
    'loading' => 'Жүктелуде...',
    'activate' => 'Қосу',
    'current_plan' => 'Ағымдағы тариф',
    'change_next_period' => 'Келесі кезеңнен ауыстыру',
    'cancel' => 'Болдырмау',
    'resume' => 'Қайта қосу',
    'autorenew_on' => 'автоұзарту: қосулы',
    'autorenew_off' => 'автоұзарту: өшірулі',
    'active' => 'БЕЛСЕНДІ',
    'inactive' => 'БЕЛСЕНДІ ЕМЕС',
    'subscription_inactive' => 'Жазылым белсенді емес',
    'confirm_cancel' => 'Автоұзартуды өшіреміз бе? Жазылым төленген мерзім аяқталғанша жұмыс істейді.',
    'session_expired' => 'Сессия аяқталды. Қайта кіріңіз.',
    'insufficient_funds' => 'Қаражат жеткіліксіз.',
    'plan_scheduled' => 'Тариф жоспарланды. Ағымдағы тариф мына күнге дейін:',
    'sub_activated_until' => 'Жазылым қосылды. Мына күнге дейін:',
    'daily_limit_reached' => 'Бүгінгі тапсырыс қабылдау лимиті аяқталды.',
    // BUG FIX: добавлены ключи, отсутствовавшие в kk-секции
    'switchToMaster' => 'Мастер болу',
    'switchToClient' => 'Клиент болу',
    'week' => 'Апта',
    'month' => 'Ай',
    'toastNoNewMessages' => 'Жаңа хабарламалар жоқ',
  ],
];